### ISSUE TITLE
Hub/Control-plane Application finalizer is not automatically removed in managed mode upon deletion

### ISSUE THREAD

**Issue by mikeshng** [argoproj-labs/argocd-agent#348]
**Describe the bug**
When deleting an Application (with `resources-finalizer.argocd.argoproj.io` finalizer) in managed mode from the hub/control-plane, the Application resource remains stuck in a deleted state. The finalizer is never removed from the Application resource on the hub, preventing the deletion from completing. This forces the user to manually remove the finalizer so the resource can be fully deleted.

**Steps to reproduce the behaviour**
1. Create an Application on the hub in managed mode, including the `resources-finalizer.argocd.argoproj.io` finalizer.
2. Initiate a `kubectl delete` on the hub for the Application.
3. Observe that the Application doesn't get deleted due to the finalizer not being removed automatically.
4. Observed that the corresponding managed/spoke cluster Application is not being deleted.
5. Confirm that manual removal of the finalizer is necessary to complete deletion.

**Expected behavior**
When the user issues a delete on the hub in managed mode, the agent should propagate the deletion to the spoke cluster. Once the Application’s resources are cleaned up on the spoke, Argo CD on the spoke should remove the finalizer. This change should propagate back to the hub, and the finalizer on the hub should automatically be removed, allowing the Application resource to be fully deleted without manual steps.

**Additional context**
Example:
```
kubectl apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: cluster1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
EOF
```

Current workaround:

`kubectl -n cluster1 delete app guestbook --wait=false; kubectl -n cluster1 patch app guestbook -p '{"metadata":{"finalizers":[]}}' --type=merge`

Slack thread in the argocd-agent channel: https://cloud-native.slack.com/archives/C07L5SX6A9J/p1743119422524829
