### ISSUE TITLE
missing permissions to read namespaced resources

### ISSUE THREAD

**Issue by ATGardner** [argoproj-labs/argocd-agent#426]
**Describe the bug**
the principal and agent RoleBinding manifests have subjects without a namespace, so they don't effect the ServiceAccount's permissions.

**Steps to reproduce the behaviour**
1. deploy the principal using `kubectl apply -n argocd -k "https://github.com/atgardner/argocd-agent.git/install/kubernetes/agent?ref=main"`
2. look at the effective permissions of the `argocd-agent-principal`

**Expected behavior**
it should have permissions on secrets, events and configmaps, but it only has the ClusterRole connected to it.

**Additional context**
adding `namespace: default` in the manifests, and instructing the user to put an explicit `namespace` in their own `kustomization.yaml` file would update both the RoleBinding and ClusterRoleBinding subjects to the correct namespace:
```yaml
namespace: argocd

resources:
- https://github.com/atgardner/argocd-agent.git/install/kubernetes/principal?ref=main
```
